import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ReportStatus } from '../constants/report-status.enum';

export class PatientInfoDto {
  @ApiProperty({ description: 'Patient UUID', example: 'uuid' })
  id: string;

  @ApiProperty({ description: 'Patient ID', example: 'PAT-20241110-0001' })
  patientId: string;

  @ApiProperty({ description: 'Patient name', example: 'John Doe' })
  name: string;
}

export class DoctorReviewInfoDto {
  @ApiProperty({ description: 'Review UUID', example: 'uuid' })
  id: string;

  @ApiPropertyOptional({ description: 'Doctor remarks', example: 'All values within normal range' })
  remarks: string | null;

  @ApiPropertyOptional({ description: 'Signed at timestamp', example: '2024-11-10T07:00:00.000Z' })
  signedAt: Date | null;
}

export class UserInfoDto {
  @ApiProperty({ description: 'User UUID', example: 'uuid' })
  id: string;

  @ApiProperty({ description: 'User email', example: 'admin@lims.com' })
  email: string;

  @ApiProperty({ description: 'User full name', example: 'John Admin' })
  fullName: string;
}

export class ReportResponseDto {
  @ApiProperty({ description: 'Report UUID', example: 'uuid' })
  id: string;

  @ApiProperty({ description: 'Patient ID', example: 'uuid' })
  patientId: string;

  @ApiProperty({ description: 'Report number', example: 'RPT-20241110-0001' })
  reportNumber: string;

  @ApiPropertyOptional({ description: 'Doctor review ID', example: 'uuid' })
  doctorReviewId: string | null;

  @ApiProperty({ description: 'Report status', enum: ReportStatus, example: ReportStatus.COMPLETED })
  status: ReportStatus;

  @ApiPropertyOptional({ description: 'PDF URL', example: 'uploads/reports/RPT-20241110-0001.pdf' })
  pdfUrl: string | null;

  @ApiPropertyOptional({ description: 'Generated at timestamp', example: '2024-11-10T08:00:00.000Z' })
  generatedAt: Date | null;

  @ApiPropertyOptional({ description: 'Generated by user ID', example: 'uuid' })
  generatedBy: string | null;

  @ApiProperty({ description: 'Created at timestamp', example: '2024-11-10T08:00:00.000Z' })
  createdAt: Date;

  @ApiProperty({ description: 'Updated at timestamp', example: '2024-11-10T08:00:00.000Z' })
  updatedAt: Date;

  @ApiPropertyOptional({ description: 'Patient information', type: PatientInfoDto })
  patient?: PatientInfoDto;

  @ApiPropertyOptional({ description: 'Doctor review information', type: DoctorReviewInfoDto })
  doctorReview?: DoctorReviewInfoDto;

  @ApiPropertyOptional({ description: 'Generated by user information', type: UserInfoDto })
  generatedByUser?: UserInfoDto;
}

export class GenerateReportResponseDto extends ReportResponseDto {}





